POST http://localhost:3000/api/auth/login
content-type: application/json

{
    "email": "testIgor5@gmail.com",
    "password": "testIgor5"
}

###
POST http://localhost:3000/api/auth/login
content-type: application/json

{
    "email": "nhi.mehl@gmail.com",
    "password": "Seecee5e"
}

###
POST http://localhost:3000/api/auth/register
content-type: application/json

###
POST http://localhost:3000/api/auth/register
content-type: application/json
{
  "email": "testIgor5@gmail.com",
  "password": "testIgor5",
  "first_name": "Les Grands",
  "last_name": "AAA",
  "address": "4 Rue des boulets",
  "zip_code": "75001",
  "country": "france",
  "city": "Paris",
  "phone_number": "0173004567"
}

###
DELETE http://localhost:3000/api/users/16
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MTQsImlhdCI6MTczNzk3NTE0MCwiZXhwIjoxNzM3OTc4NzQwfQ.u1lorJiKPrnSbseDzPimZju6BvYKbDUsKX4ZrrQQjXw
Content-type: application/json


###
POST http://localhost:3000/api/orders/create_order
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MTYsImlhdCI6MTcyNzg5NzEzNywiZXhwIjoxNzI3OTAwNzM3fQ.cJ_VVVH_7UuDMa_jejNd_bzkO4EziyNtRkAXtBSJsyY
content-type: application/json

{
  "amount": 149,
  "orderLine": [
    {
      "project_tree_id": 4,
      "quantity": 1,
      "amount": 49
    },
    {
      "project_tree_id": 12,
      "quantity": 2,
      "amount": 100
    }
  ]
}

###
POST http://localhost:3000/api/auth/logout
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MTMsImlhdCI6MTcyNjQ5ODYwMSwiZXhwIjoxNzI2NTAyMjAxfQ.4MhmH674DahScGnT-wGnMtAeh3IjWoOW9dAm9cuEVS4
content-type: application/json



###
GET http://localhost:3000/api/users/profile
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MTQsImlhdCI6MTczNzk3NDMwNSwiZXhwIjoxNzM3OTc3OTA1fQ.lfHPB_kBgvOV_O1rpaORnF7vz48S0bCXltNIQhmAjnk

###vien
Get http://localhost:3000/api/project_trees/highlights

###
GET http://localhost:3000/api/orders/16
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MTYsImlhdCI6MTcyNzM4MTMzMywiZXhwIjoxNzI3Mzg0OTMzfQ.nNOi3qnrOMYG-2IUSHJ9IzejuR-LLfhaEBoPR9Zs_MQ



###
GET http://localhost:3000/api/order_line/1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MTYsImlhdCI6MTcyNzM4MTMzMywiZXhwIjoxNzI3Mzg0OTMzfQ.nNOi3qnrOMYG-2IUSHJ9IzejuR-LLfhaEBoPR9Zs_MQ

###
PUT http://localhost:3000/api/users/16
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MTYsImlhdCI6MTcyNjY3MTIxNiwiZXhwIjoxNzI2Njc0ODE2fQ.inQMJhTMIbDVYnGYFKYdzwxy-sTR4PqlPXXvLPVAw8I
content-type: application/json

{
  "first_name": "nhi",
  "last_name": "vien",
  "address": "123 blablabla",
  "zip_code": "67000",
  "country": "france",
  "city": "strasbourg",
  "phone_number": "0123456789",
  "email": "nhi@gmail.com"
}
