POST http://localhost:3000/api/auth/login
content-type: application/json

{
    "email": "testIgor5@gmail.com",
    "password": "testIgor5"
}


###
POST http://localhost:3000/api/auth/register
content-type: application/json

###
POST http://localhost:3000/api/auth/register
content-type: application/json
{
  "email": "testIgor5@gmail.com",
  "password": "testIgor5",
  "first_name": "Les Grands",
  "last_name": "AAA",
  "address": "4 Rue des boulets",
  "zip_code": "75001",
  "country": "france",
  "city": "Paris",
  "phone_number": "0173004567"
}

###
POST http://localhost:3000/api/auth/login
content-type: application/json

###
DELETE http://localhost:3000/api/users/16
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MTYsImlhdCI6MTcyNjE0Mjg4OSwiZXhwIjoxNzI2MTQ2NDg5fQ.AHQgKNL3FhrRYZe-bzkWvZPAIhrQNjyoi3XShIP5pZs
Content-type: application/json

{
    "message": "Account deleted successfully"
}

###
POST http://localhost:3000/api/orders/create_order
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MTMsImlhdCI6MTcyNjQwMDk4OCwiZXhwIjoxNzI2NDA0NTg4fQ.nHHgaxbGo-yHnj_Bdh1nvChZeArxID858X7HclI3uds
content-type: application/json

{
  "amount": 150.5,
  "orderLine": [
    {
      "project_tree_id": 3,
      "quantity": 5,
      "amount": 30.0
    },
    {
      "project_tree_id": 5,
      "quantity": 1,
      "amount": 120.5
    }
  ]
}


###
POST http://localhost:3000/api/auth/logout
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MTMsImlhdCI6MTcyNjQwMDk4OCwiZXhwIjoxNzI2NDA0NTg4fQ.nHHgaxbGo-yHnj_Bdh1nvChZeArxID858X7HclI3uds
content-type: application/json