POST http://localhost:3000/api/auth/login
Content-Type: application/json

{
  "email": "testIgorMethodePUT@gmail.com",
  "password": "testPUT",
  "first_name": "Les Grands",
  "last_name": "AAA",
  "confirmation": "testPUT",
  "zip_code": "75001",
  "country": "france",
  "city": "Paris",
  "phone_number": "0173004567"
}







PUT http://localhost:3000/api/users/14
Authorisation: Bearer OurSuperLongRandomSecretToSignOurJWTgre5ezg4jyt5j4ui64gn56bd4sfs5qe4erg5t5yjh46yu6knsw4q
content-type: application/json

{
  "email": "testIgorPUT@gmail.com",
  "password": "abc123eeze",
  "first_name": "Les Grands",
  "last_name": "AAA",
  "confirmation": "abc123eeze",
  "zip_code": "75001",
  "country": "france",
  "city": "Paris",
  "phone_number": "0173004567"
}



// commentaire pour commit


